# Generated by Django 5.2.3 on 2025-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_in_stock_product_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RM 折扣（可选）', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='百分比折扣（例如 20 代表 20%）', null=True),
        ),
    ]
