# Generated by Django 5.2.3 on 2025-06-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_attribute_alter_product_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='shop.product'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
    ]
