# Generated by Django 5.2.3 on 2025-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'session_key')},
        ),
    ]
