# Generated by Django 5.2.3 on 2025-07-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ImageField(blank=True, null=True, upload_to='products/size_charts/'),
        ),
    ]
