# Generated by Django 5.2.3 on 2025-07-01 04:58

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Size chart'),
        ),
    ]
