# Generated by Django 5.2.3 on 2025-07-01 05:44

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_image_alter_product_size_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image'),
        ),
    ]
