# Generated by Django 5.2.3 on 2025-07-01 08:03

import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='products/gallery/')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_chart',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_filebrowse',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image (FileBrowser)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_filebrowse',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Size Chart (FileBrowser)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/size_charts/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_filebrowse',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image (FileBrowser)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
