# Generated by Django 5.0.14 on 2025-07-01 09:10

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_imageasset_remove_product_image_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_filebrowse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_chart_filebrowse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_chart_upload',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
