# Generated by Django 5.0.14 on 2025-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_menuitem_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
