# Generated by Django 5.0.14 on 2025-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_footerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='open_in_new_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
