# Generated by Django 5.0.14 on 2025-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_footerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_window',
            field=models.BooleanField(default=False, verbose_name='Open in new window'),
        ),
    ]
