# Generated by Django 5.0.14 on 2025-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, to='shop.attributevalue'),
        ),
    ]
