# Generated by Django 5.0.14 on 2025-07-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_cartitem_attribute_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
