# Generated by Django 5.0.14 on 2025-07-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_banner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
