# Generated by Django 5.0.14 on 2025-07-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_attributevalue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, to='shop.attributevalue'),
        ),
    ]
