# Generated by Django 5.2.1 on 2025-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_orderitem_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_sale',
            field=models.BooleanField(default=False, verbose_name='Hot Sale'),
        ),
    ]
