# Generated by Django 5.0.14 on 2025-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_hot_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Hot Level'),
        ),
    ]
