# Generated by Django 5.2.1 on 2025-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hot_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
