# Generated by Django 5.2.1 on 2025-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_product_is_active_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
