# Generated by Django 5.0.14 on 2025-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
