# Generated by Django 5.2.1 on 2025-10-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_companyinfo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('default', 'Default Layout'), ('modern', 'Modern Layout'), ('minimal', 'Minimal Layout')], default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('theme_color', models.CharField(blank=True, max_length=20, null=True)),
                ('show_banner', models.BooleanField(default=True)),
                ('show_featured', models.BooleanField(default=True)),
                ('show_hot_sale', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
