# Generated by Django 5.2.1 on 2025-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_homepagelayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagelayout',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='homepagelayout',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
