# Generated by Django 5.2.1 on 2025-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_homepagelayout_theme_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagelayout',
            name='show_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagelayout',
            name='show_new_products',
            field=models.BooleanField(default=True),
        ),
    ]
