# Generated by Django 5.0.14 on 2025-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_homepagelayout_show_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, help_text='可显示在 landing page 上的自定义文字', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
