# Generated by Django 5.0.14 on 2025-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_landingpagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesetting',
            name='heading',
            field=models.CharField(blank=True, help_text='Landing page 标题（留空则使用公司名称）', max_length=255, null=True),
        ),
    ]
